"""image_path for space_object

Revision ID: f5fad7c676c7
Revises: a0766546b2f1
Create Date: 2022-04-23 01:06:00.295509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5fad7c676c7'
down_revision = 'a0766546b2f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('space_objects', sa.Column('image_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('space_objects', 'image_path')
    # ### end Alembic commands ###
